<?php

namespace Database\Seeders\Academia;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\AcademiaUniversity;
use App\Models\AcademiaMedicalResidency;
use App\Models\AcademiaFacility;

class CaliforniaDataSeeder extends Seeder
{
    public function run()
    {
        $state = State::updateOrCreate(
            ['slug' => 'california'],
            ['name' => 'California', 'code' => 'CA']
        );

        $universities = [
            ['name' => 'Academy of Art University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'American Film Institute Conservatory', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'American Jewish University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Antioch University Los Angeles', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Antioch University Santa Barbara', 'psych' => ['BA', 'MA', 'MA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'ArtCenter College of Design', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Azusa Pacific University', 'psych' => ['BS', 'BA', 'MS', 'MA', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Bethesda University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Biola University', 'psych' => ['BS', 'BA', 'MA', 'PsyD', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'California Baptist University', 'psych' => ['BS', 'BS (OL)', 'BA', 'BA (OL)', 'MS', 'MS (OL)', 'MA', 'PsyD'], 'neuro' => [], 'ol' => true],
            ['name' => 'California College of the Arts', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'California Institute of the Arts', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'California Institute of Technology', 'psych' => ['PhD'], 'neuro' => ['BS', 'PhD'], 'ol' => false],
            ['name' => 'California Lutheran University', 'psych' => ['BS', 'BA', 'MS', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'California Miramar University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal Polytechnic State University', 'psych' => ['BS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State Polytechnic University, Humboldt', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State Polytechnic University, Pomona', 'psych' => ['BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Bakersfield', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University Channel Islands', 'psych' => ['BA', 'BA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Cal State University, Chico', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Dominguez Hills', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, East Bay', 'psych' => ['BS', 'BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Fresno', 'psych' => ['BA', 'MA', 'EdS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Fullerton', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Long Beach', 'psych' => ['BS', 'BA', 'BA (OL)', 'MS', 'MA'], 'neuro' => [], 'ol' => true],
            ['name' => 'Cal State University, Los Angeles', 'psych' => ['BS', 'BA', 'MS', 'MA', 'EdS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University Maritime Academy', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Monterey Bay', 'psych' => ['BA', 'EdS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Northridge', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, Sacramento', 'psych' => ['BS', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cal State University, San Bernardino', 'psych' => ['BA', 'MS', 'MA', 'EdS'], 'neuro' => [], 'ol' => false],
            ['name' => 'California State University San Marcos', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'California State University, Stanislaus', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],

            ['name' => 'California Western School of Law', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'California Institute of Integral Studies', 'psych' => ['BS (OL)', 'MA', 'PsyD', 'PhD'], 'neuro' => [], 'ol' => true],
            ['name' => 'Chapman University', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Charles R. Drew Univ of Med & Sci', 'psych' => ['BS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Chicago School of Professional Psychology', 'psych' => ['BA', 'MS', 'MS (OL)', 'MA', 'MA (OL)', 'PsyD', 'PhD'], 'neuro' => [], 'ol' => true],
            ['name' => 'Claremont McKenna College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Claremont Graduate University', 'psych' => ['MA', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Concordia University Irvine', 'psych' => ['BA', 'MA', 'MAEd', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Dharma Realm Buddhist University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Dominican Sch of Philosophy & Theology', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Dominican University of California', 'psych' => ['BS', 'BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Fresno Pacific University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Golden Gate University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Harvey Mudd College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Holy Names University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Hope International University', 'psych' => ['BA', 'BA (OL)', 'MS', 'MA', 'DMFT'], 'neuro' => [], 'ol' => true],
            ['name' => 'Humboldt State University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Humphreys University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Irell and Manella Grad School of Bio Sci', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Jessup University', 'psych' => ['BS', 'BS (OL)', 'BA', 'BA (OL)', 'MA'], 'neuro' => [], 'ol' => true],
            ['name' => 'John Paul the Great Catholic University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Keck Graduate Institute', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'La Sierra University', 'psych' => ['BA', 'MA', 'EdS', 'EdD', 'PhD'], 'neuro' => ['BS', 'BA'], 'ol' => false],
            ['name' => 'Laguna College of Art and Design', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Life Pacific College', 'psych' => ['BA', 'BA (OL)', 'MA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Loma Linda University', 'psych' => ['MS', 'MS (OL)', 'PsyD', 'PhD'], 'neuro' => ['MS', 'PhD'], 'ol' => true],
            ['name' => 'Loyola Marymount University', 'psych' => ['BA', 'MA', 'EdS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Marshall B. Ketchum University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'The Master\'s University', 'psych' => ['BA', 'MA', 'DMin'], 'neuro' => [], 'ol' => false],
            ['name' => 'Menlo College', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Mills College at Northeastern University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Mount St. Mary\'s University', 'psych' => ['BS', 'MS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'National University', 'psych' => ['BA', 'MS', 'MA', 'PsyD', 'DMFT', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'NewSchool of Architecture and Design', 'psych' => [], 'neuro' => [], 'ol' => false],

            ['name' => 'Notre Dame de Namur University', 'psych' => ['BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Occidental College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Otis College of Art and Design', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Pacifica Graduate Institute', 'psych' => ['MA', 'MA (OL)', 'PsyD', 'PhD', 'PhD (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Pacific Oaks College', 'psych' => ['BA', 'BA (OL)', 'MA', 'MA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Pacific Union College', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Palo Alto University', 'psych' => ['BS', 'MS', 'MA', 'PsyD', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Pepperdine University', 'psych' => ['BA', 'MS', 'MS (OL)', 'MA', 'MA (OL)', 'PsyD'], 'neuro' => [], 'ol' => true],
            ['name' => 'Pitzer College', 'psych' => ['BA', 'BA+MA', 'MA'], 'neuro' => ['BA'], 'ol' => false],
            ['name' => 'Point Loma Nazarene University', 'psych' => ['BA', 'MS', 'MA', 'MA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Pomona College', 'psych' => ['BA'], 'neuro' => ['BA'], 'ol' => false],
            ['name' => 'Providence Christian College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'RAND School of Public Policy', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Saint Mary\'s College of California', 'psych' => ['BS', 'MA', 'EdS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Samuel Merritt University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'San Diego Christian College', 'psych' => ['BA', 'BA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'San Diego State University', 'psych' => ['BA', 'MS', 'MA', 'EdS', 'PhD'], 'neuro' => ['BA', 'MA'], 'ol' => false],
            ['name' => 'San Francisco Conservatory of Music', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'San Francisco State University', 'psych' => ['BA', 'BA (OL)', 'MS', 'MA'], 'neuro' => [], 'ol' => true],
            ['name' => 'San Joaquin College of Law', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'San Jose State University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Santa Clara University', 'psych' => ['BS', 'MA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Saybrook University', 'psych' => ['MS', 'MA', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Scripps College', 'psych' => ['BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Simpson University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Soka University of America', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Sofia University', 'psych' => ['BA', 'MA', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Sonoma State University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Southern California Institute of Architecture', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Southwestern Law School', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Stanford University', 'psych' => ['BA', 'MS', 'MA', 'PhD'], 'neuro' => ['MS', 'PhD'], 'ol' => false],
            ['name' => 'Thomas Aquinas College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Thomas Jefferson School of Law', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Touro University California', 'psych' => [], 'neuro' => [], 'ol' => false],

            ['name' => 'United States University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'University of California Berkeley', 'psych' => ['BA', 'PhD'], 'neuro' => ['BA', 'PhD'], 'ol' => false],
            ['name' => 'University of California Davis', 'psych' => ['BS', 'A.B.', 'MA', 'PhD'], 'neuro' => ['BS', 'A.B.', 'MA', 'PhD'], 'ol' => false],
            ['name' => 'University of California Irvine', 'psych' => ['BA', 'MLFP', 'PhD'], 'neuro' => ['BS', 'PhD'], 'ol' => false],
            ['name' => 'University of California Los Angeles', 'psych' => ['BA', 'MS', 'PhD'], 'neuro' => ['BS', 'PhD'], 'ol' => false],
            ['name' => 'University of California Merced', 'psych' => ['BA', 'PhD'], 'neuro' => ['BS', 'BA'], 'ol' => false],
            ['name' => 'University of California Riverside', 'psych' => ['BS', 'BA', 'PhD'], 'neuro' => ['BS', 'BA', 'PhD'], 'ol' => false],
            ['name' => 'University of California San Diego', 'psych' => ['BS', 'BA', 'PhD'], 'neuro' => ['BS', 'BA', 'PhD'], 'ol' => false],
            ['name' => 'University of California San Francisco', 'psych' => ['BA', 'MA', 'PhD'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'University of California Santa Barbara', 'psych' => ['BS', 'MA', 'MED', 'PhD'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'University of California Santa Cruz', 'psych' => ['BS', 'BA', 'PhD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Univ of Cal Coll of the Law, San Francisco', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'University of La Verne', 'psych' => ['BS', 'MS', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'University of the Pacific', 'psych' => ['BS', 'MA', 'EdS', 'EdD', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'University of Redlands', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'University of San Diego', 'psych' => ['BA', 'MA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'University of San Francisco', 'psych' => ['BA', 'MA', 'PsyD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'University of St. Augustine for Health Sci', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'University of Silicon Valley', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'University of Southern California', 'psych' => ['BA', 'MS', 'MEC', 'EdD (OL)', 'PhD'], 'neuro' => ['BS', 'BA', 'MS', 'PhD'], 'ol' => true],
            ['name' => 'The University of West Los Angeles', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'University of the West', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Vanguard University', 'psych' => ['BA', 'BA (OL)', 'MS'], 'neuro' => [], 'ol' => true],
            ['name' => 'West Coast University-Los Angeles', 'psych' => ['MS (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Western University of Health Sciences', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Westmont College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Whittier College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Woodbury University', 'psych' => [], 'neuro' => [], 'ol' => false],
        ];

        foreach ($universities as $uni) {
            AcademiaUniversity::create([
                'state_id' => $state->id,
                'name' => $uni['name'],
                'psychology_degrees' => $uni['psych'],
                'neuroscience_degrees' => $uni['neuro'],
                'has_online_options' => $uni['ol'],
            ]);
        }

        $residencies = [
            ['name' => 'UCLA-Kern Medical Center', 'loc' => 'Bakersfield', 'deg' => ['MD-DO']],
            ['name' => 'University of California (Irvine)', 'loc' => 'Orange', 'deg' => ['MD-DO']],
            ['name' => 'University of Southern California/Los Angeles General Medical Center (USC/LA General)', 'loc' => 'Jonesboro', 'deg' => ['MD-DO']],
            ['name' => 'University of California Davis Health', 'loc' => 'Sacramento', 'deg' => ['MD-DO']],
            ['name' => 'Los Angeles Co-UCLA Medical Center Psychiatry Residency Program', 'loc' => 'Torrance', 'deg' => ['MD-DO']],
            ['name' => 'University of California (San Francisco)/Fresno', 'loc' => 'Fresno', 'deg' => ['MD-DO']],
            ['name' => 'California Pacific Medical Center', 'loc' => 'San Francisco', 'deg' => ['MD-DO']],
            ['name' => 'Loma Linda Univ Health Ed Consortium Psychiatry Residency', 'loc' => 'Redlands', 'deg' => ['MD-DO']],
            ['name' => 'UCLA David Geffen School of Medicine/UCLA Medical Center (MD-DO)', 'loc' => 'Los Angeles', 'deg' => ['MD-DO']],
            ['name' => 'University of California (San Francisco)', 'loc' => 'San Francisco', 'deg' => ['MD-DO']],
            ['name' => 'Univ of California (San Diego) Med Ctr Psychiatry Residency Program', 'loc' => 'San Diego', 'deg' => ['MD-DO']],
            ['name' => 'San Mateo County Behavioral Health and Recovery Services', 'loc' => 'San Mateo', 'deg' => ['MD-DO']],
            ['name' => 'Stanford Health Care-Sponsored Stanford University', 'loc' => 'Palo Alto', 'deg' => ['MD-DO']],
            ['name' => 'UCLA David Geffen School of Medicine/UCLA Medical Center/VA Greater Los Angeles Healthcare System', 'loc' => 'Los Angeles', 'deg' => ['MD-DO']],
            ['name' => 'Kaweah Delta Health Care District (KDHCD) Psychiatry Residency', 'loc' => 'Visalia', 'deg' => ['MD-DO']],
            ['name' => 'Naval Medical Center (San Diego) Psychiatry Residency', 'loc' => 'San Diego', 'deg' => ['MD-DO']],
            ['name' => 'Kaiser Permanente Southern California', 'loc' => 'Fontana', 'deg' => ['MD-DO']],
            ['name' => 'University of California Riverside School of Medicine', 'loc' => 'Riverside', 'deg' => ['MD-DO']],
            ['name' => 'Arrowhead Regional Medical Center', 'loc' => 'Colton', 'deg' => ['MD-DO']],
            ['name' => 'Kaiser Permanente Northern California (Oakland)', 'loc' => 'Oakland', 'deg' => ['MD-DO']],
            ['name' => 'Kaiser Permanente Northern California (San Jose) Psychiatry Residency Program', 'loc' => 'San Jose', 'deg' => ['MD-DO']],
            ['name' => 'Olive View/UCLA Medical Center', 'loc' => 'Sylmar', 'deg' => ['MD-DO']],
            ['name' => 'Riverside University Health System', 'loc' => 'Riverside', 'deg' => ['MD-DO']],
            ['name' => 'Community Memorial Health System Psychiatry Residency', 'loc' => 'Ventura', 'deg' => ['MD-DO']],
            ['name' => 'St. Joseph\'s Medical Center', 'loc' => 'Stockton', 'deg' => ['MD-DO']],
            ['name' => 'Mission Community Hospital', 'loc' => 'Panorama City', 'deg' => ['MD-DO']],
            ['name' => 'College Medical Center', 'loc' => 'Long Beach', 'deg' => ['MD-DO']],
            ['name' => 'Healthy Rural California, Inc. Psychiatry Residency Program', 'loc' => 'Chico', 'deg' => ['MD-DO']],
            ['name' => 'Family Health Centers of San Diego', 'loc' => 'San Diego', 'deg' => ['MD-DO']],
            ['name' => 'Oroville Hospital', 'loc' => 'Oroville', 'deg' => ['MD-DO']],
            ['name' => 'Loma Linda University Health Education Consortium Psychiatry Residency Program', 'loc' => 'Patton', 'deg' => ['MD-DO']],
            ['name' => 'Eisenhower Medical Center', 'loc' => 'Rancho Mirage', 'deg' => ['MD-DO']],
            ['name' => 'Keck School of Medicine of USC', 'loc' => 'Los Angeles', 'deg' => ['MD-DO']],
            ['name' => 'Prime West Consortium', 'loc' => 'Lynwood', 'deg' => ['MD-DO']],
            ['name' => 'Kaiser Permanente Northern Cal Psychiatry Residency', 'loc' => 'Sacramento', 'deg' => ['MD-DO']],
            ['name' => 'Imperial County Behavioral Health Services', 'loc' => 'El Centro', 'deg' => ['MD-DO']],
            ['name' => 'Brain Health USA-Van Nuys', 'loc' => 'Van Nuys', 'deg' => ['MD-DO']],
            ['name' => 'Kaiser Permanente Bernard J. Tyson School of Medicine', 'loc' => 'Pasadena', 'deg' => ['MD-PhD']],
            ['name' => 'Loma Linda University School of Medicine', 'loc' => 'Loma Linda', 'deg' => ['MD-PhD']],
            ['name' => 'Stanford University School of Medicine', 'loc' => 'Stanford', 'deg' => ['MD-PhD']],
            ['name' => 'University of California, Davis School of Medicine', 'loc' => 'Davis', 'deg' => ['MD-PhD']],
            ['name' => 'University of California, Irvine School of Medicine', 'loc' => 'Irvine', 'deg' => ['MD-PhD']],
            ['name' => 'University of California, Los Angeles School of Medicine', 'loc' => 'Los Angeles', 'deg' => ['MD-PhD']],
            ['name' => 'University of California, San Diego School of Medicine', 'loc' => 'La Jolla', 'deg' => ['MD-PhD']],
            ['name' => 'Univ of California, San Francisco School of Medicine', 'loc' => 'San Francisco', 'deg' => ['MD-PhD']],
            ['name' => 'Keck School of Med of the Univ of Southern California', 'loc' => 'Los Angeles', 'deg' => ['MD-PhD']],
        ];

        foreach ($residencies as $res) {
            AcademiaMedicalResidency::create([
                'state_id' => $state->id,
                'program_name' => $res['name'],
                'location' => $res['loc'],
                'degree_types' => $res['deg'],
            ]);
        }

        $facilities = [
            // Veterans Affairs (VA) Residential Treatment Facilities
            ['name' => 'Jennifer Moreno Department of Veterans Affairs Medical Center', 'loc' => 'San Diego', 'type' => 'va_facility'],
            ['name' => 'Palo Alto VA Medical Center', 'loc' => 'Palo Alto', 'type' => 'va_facility'],
            ['name' => 'Palo Alto VA Medical Center', 'loc' => 'Menlo Park', 'type' => 'va_facility'],
            ['name' => 'San Francisco VA Medical Center', 'loc' => 'San Francisco', 'type' => 'va_facility'],
            ['name' => 'West Los Angeles VA Medical Center', 'loc' => 'Los Angeles', 'type' => 'va_facility'],

            // State Institutions
            ['name' => 'Atascadero State Hospital', 'loc' => 'Atascadero', 'type' => 'state_institution'],
            ['name' => 'Aurora Charter Oak Hospital', 'loc' => 'Covina', 'type' => 'state_institution'],
            ['name' => 'Aurora San Diego Hospital', 'loc' => 'San Diego', 'type' => 'state_institution'],
            ['name' => 'BHC Alhambra Hospital', 'loc' => 'Rosemead', 'type' => 'state_institution'],
            ['name' => 'Coalinga State Hospital', 'loc' => 'Coalinga', 'type' => 'state_institution'],
            ['name' => 'Community Behavioral Health Center', 'loc' => 'Fresno', 'type' => 'state_institution'],
            ['name' => 'Del Amo Hospital', 'loc' => 'Torrance', 'type' => 'state_institution'],
            ['name' => 'Devereux Advanced Behavioral Health', 'loc' => 'Santa Barbara', 'type' => 'state_institution'],
            ['name' => 'Didi Hirsch Community Mental Health Center', 'loc' => 'Culver City', 'type' => 'state_institution'],
            ['name' => 'Fremont Hospital', 'loc' => 'Fremont', 'type' => 'state_institution'],
            ['name' => 'Heritage Oaks Hospital', 'loc' => 'Sacramento', 'type' => 'state_institution'],
            ['name' => 'Alameda Health Behavioral Services', 'loc' => 'San Leandro', 'type' => 'state_institution'],
            ['name' => 'Las Encinas Hospital', 'loc' => 'Pasadena', 'type' => 'state_institution'],
            ['name' => 'Metropolitan State Hospital', 'loc' => 'Norwalk', 'type' => 'state_institution'],
            ['name' => 'Napa State Hospital', 'loc' => 'Napa', 'type' => 'state_institution'],
            ['name' => 'Pacific Grove Hospital', 'loc' => 'Riverside', 'type' => 'state_institution'],
            ['name' => 'Patton State Hospital', 'loc' => 'San Bernardino', 'type' => 'state_institution'],
            ['name' => 'San Jose Behavioral Health Hospital', 'loc' => 'San Jose', 'type' => 'state_institution'],
            ['name' => 'Saint Joseph\'s Behavioral Health Center', 'loc' => 'Stockton', 'type' => 'state_institution'],
            ['name' => 'Sharp Behavioral Health', 'loc' => 'San Diego', 'type' => 'state_institution'],
            ['name' => 'Sierra Vista Hospital', 'loc' => 'Sacramento', 'type' => 'state_institution'],
            ['name' => 'Sutter Center for Psychiatry', 'loc' => 'Sacramento', 'type' => 'state_institution'],
            ['name' => 'UCLA Resnick Neuropsychiatric Hospital', 'loc' => 'Los Angeles', 'type' => 'state_institution'],
            ['name' => 'Vista del Mar Hospital', 'loc' => 'Ventura', 'type' => 'state_institution'],

            // University Hospital (Client Placeholder if relevant)
            ['name' => 'Univ of Alabama at Birmingham Center for Psychiatric Medicine', 'loc' => 'Birmingham', 'type' => 'university_hospital'],
        ];

        foreach ($facilities as $fac) {
            AcademiaFacility::create([
                'state_id' => $state->id,
                'name' => $fac['name'],
                'location' => $fac['loc'],
                'type' => $fac['type'],
            ]);
        }
    }
}
