<?php

namespace Database\Seeders\Academia;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\AcademiaUniversity;
use App\Models\AcademiaMedicalResidency;
use App\Models\AcademiaFacility;

class NewYorkDataSeeder extends Seeder
{
    public function run()
    {
        $state = State::updateOrCreate(
            ['slug' => 'new-york'],
            ['name' => 'New York', 'code' => 'NY']
        );

        $universities = [
            ['name' => 'Adelphi University', 'psych' => ['BA', 'BA+MA', 'MA', 'PsyD', 'PhD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Albany Law School', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Albany Medical College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Albany College of Pharm and Health Sci', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Alfred State College', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Alfred University', 'psych' => ['BA', 'MA', 'MSEd', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Bank Street College of Education', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Bard College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Barnard College', 'psych' => ['BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Baruch College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Berkeley College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Binghamton University', 'psych' => ['BA', 'PhD'], 'neuro' => ['BS', 'PhD'], 'ol' => false],
            ['name' => 'Boricua College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Brooklyn College', 'psych' => ['BS', 'BA', 'MS', 'MA', 'MSEd'], 'neuro' => [], 'ol' => false],
            ['name' => 'Brooklyn Law School', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Bryant and Stratton College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Buffalo State University', 'psych' => ['BS', 'BA', 'BS+MS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Canisius College', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'City College of New York', 'psych' => ['BS', 'BS (OL)', 'BA', 'BA (OL)', 'MA', 'PhD'], 'neuro' => [], 'ol' => true],
            ['name' => 'Clarkson University', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Colgate University', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'College of Staten Island', 'psych' => ['BS', 'BA', 'MA'], 'neuro' => ['MS'], 'ol' => false],
            ['name' => 'The College of Westchester', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Columbia University', 'psych' => ['BA', 'MA', 'EdM', 'PhD'], 'neuro' => ['BS', 'PhD'], 'ol' => false],
            ['name' => 'Columbia University- Teacher\'s College', 'psych' => ['MA', 'EdM', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Cooper Union for the Adv of Science & Art', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Cornell University', 'psych' => ['BS', 'BA', 'MA', 'PhD'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'Culinary Institute of America', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'CUNY School of Law', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'CUNY Graduate Center', 'psych' => ['PhD'], 'neuro' => ['MS', 'PhD'], 'ol' => false],
            ['name' => 'CUNY York College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Daemen University', 'psych' => ['BS', 'BA', 'MS', 'MS (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Davis College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Dominican University', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'D\'Youville University', 'psych' => ['BA', 'MS', 'PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Elmira College', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Empire State University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Excelsior University', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Fashion Institute of Technology', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Farmingdale State College', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Five Towns College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Fordham University', 'psych' => ['BS', 'MS', 'MSE', 'MSEd', 'PhD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Hamilton College', 'psych' => ['BS', 'BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Hartwick College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Helene Fuld College of Nursing', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Hilbert College', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Hobart and William Smith Colleges', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Hofstra University', 'psych' => ['BS', 'BA', 'MS', 'MA', 'MSEd', 'PsyD', 'PhD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Houghton University', 'psych' => ['BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Hunter College', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Icahn School of Medicine at Mt Sinai', 'psych' => ['MA'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'Iona University', 'psych' => ['BA', 'BA+MA', 'MA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Ithaca College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'John Jay College of Criminal Justice', 'psych' => ['BA', 'MA', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'The Juilliard School', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Keuka College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'King\'s College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Le Moyne College', 'psych' => ['BS', 'BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Lehman College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'LIM College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Long Island University- Brooklyn', 'psych' => ['BA', 'MS', 'MA', 'MSEd', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Long Island University- Post', 'psych' => ['BA', 'MS', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Manhattan College', 'psych' => ['BS', 'BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Manhattan School of Music', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Manhattanville College', 'psych' => ['BA'], 'neuro' => ['BS', 'BA', 'BA+MS', 'MS'], 'ol' => false],
            ['name' => 'Maria College', 'psych' => ['BS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Marist University', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Marymount Manhattan College', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],

            ['name' => 'Medgar Evers College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Mercy University', 'psych' => ['BS', 'BS+MS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Metropolitan College of New York', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Molloy College', 'psych' => ['BS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Monroe University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Morrisville State College', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Mount Saint Mary College', 'psych' => ['BA', 'BA+MS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Nazareth University', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'The New School', 'psych' => ['BA', 'MA', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'New York Academy of Art', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York City College of Technology', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York College of Podiatric Medicine', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York Institute of Technology', 'psych' => ['BS', 'BS+MS', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'New York Law School', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York Medical College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York School of Interior Design', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'New York University', 'psych' => ['BS', 'BA', 'MA', 'PhD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Niagara University', 'psych' => ['BS', 'BA', 'MS', 'MSEd'], 'neuro' => [], 'ol' => false],
            ['name' => 'Pace University', 'psych' => ['BA', 'BA+MA', 'MA', 'MSEd', 'PsyD', 'PhD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Paul Smith\'s College', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Plaza College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Pratt Institute', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Queens College', 'psych' => ['BA', 'MS', 'MA', 'PhD'], 'neuro' => ['BA', 'PhD'], 'ol' => false],
            ['name' => 'Relay Graduate School of Education', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Roberts Wesleyan University', 'psych' => ['BS', 'BA', 'MS', 'PsyD'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Rochester Institute of Technology', 'psych' => ['BS', 'MS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'The Rockefeller University', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Russell Sage College', 'psych' => ['BS', 'MS', 'MA', 'MA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'Sarah Lawrence College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'School of Visual Arts', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Siena College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Skidmore College', 'psych' => ['BA'], 'neuro' => ['BA'], 'ol' => false],
            ['name' => 'St. Bonaventure University', 'psych' => ['BS', 'BA', 'MSEd (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'St. Francis College', 'psych' => ['BA', 'MA'], 'neuro' => [], 'ol' => false],
            ['name' => 'St. John\'s University', 'psych' => ['BA', 'BA+MA', 'MS', 'MA, MSEd', 'PsyD', 'PhD'], 'neuro' => ['MS'], 'ol' => false],
            ['name' => 'St. John Fisher College', 'psych' => ['BS', 'BA', 'MS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'St. Joseph\'s University- Brooklyn', 'psych' => ['BS', 'BA', 'BA+MBA'], 'neuro' => [], 'ol' => false],
            ['name' => 'St. Joseph\'s University- Long Island', 'psych' => ['BS', 'BA', 'BA+MBA'], 'neuro' => [], 'ol' => false],
            ['name' => 'St. Lawrence University', 'psych' => ['BS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'St. Thomas Aquinas College', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Brockport', 'psych' => ['BS', 'BS+MA', 'MS', 'MA, MSEd'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Canton', 'psych' => ['BS', 'BS (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'State Univ of NY (SUNY) Cobleskill', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Cortland', 'psych' => ['BS', 'BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Delhi', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Fredonia', 'psych' => ['BS', 'BA', 'MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Geneseo', 'psych' => ['BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Maritime College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Downstate Med Ctr', 'psych' => [], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) New Paltz', 'psych' => ['BS', 'BA, BA+MS, MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Oneonta', 'psych' => ['BS, MSEd'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Oswego', 'psych' => ['BA, MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Plattsburgh', 'psych' => ['BS, BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Polytechnic Inst', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Potsdam', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'State Univ of NY (SUNY) Purchase', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'SUNY Coll of Environmental Sci & Forestry', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'SUNY College at Old Westbury', 'psych' => ['BS, BA, MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'SUNY College of Optometry', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Stony Brook University', 'psych' => ['BS, BA, MA, PhD'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'Syracuse University', 'psych' => ['BS, BA, MS, PhD'], 'neuro' => ['BS, BA'], 'ol' => false],
            ['name' => 'Touro University', 'psych' => ['BA, MS, MA, PsyD'], 'neuro' => [], 'ol' => false],
            ['name' => 'Trocaire College', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Union College', 'psych' => ['BS'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'US Merchant Marine Academy', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'US Military Academy', 'psych' => ['BS'], 'neuro' => [], 'ol' => false],
            ['name' => 'University at Albany', 'psych' => ['BA, MS, MA, PsyD, PhD'], 'neuro' => ['PhD'], 'ol' => false],
            ['name' => 'University at Buffalo', 'psych' => ['BS, BA, MS, MA, PhD, MD-PhD'], 'neuro' => ['BS, BS+MS, PhD, MD-PhD'], 'ol' => false],

            ['name' => 'University of Mount Saint Vincent', 'psych' => ['BA, BA (OL)'], 'neuro' => [], 'ol' => true],
            ['name' => 'University of Rochester', 'psych' => ['BA, MS, PhD, EdD'], 'neuro' => ['BS, PhD'], 'ol' => false],
            ['name' => 'Upstate Medical University', 'psych' => ['MS'], 'neuro' => [], 'ol' => false],
            ['name' => 'Utica University', 'psych' => ['BS, BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Vassar College', 'psych' => ['BA'], 'neuro' => ['BA'], 'ol' => false],
            ['name' => 'Villa Maria College', 'psych' => ['BA'], 'neuro' => [], 'ol' => false],
            ['name' => 'Vaughn College of Aeronautics & Tech', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Wagner College', 'psych' => ['Bs, BA'], 'neuro' => ['BS'], 'ol' => false],
            ['name' => 'Webb Institute', 'psych' => [], 'neuro' => [], 'ol' => false],
            ['name' => 'Yeshiva University', 'psych' => ['BA, MS, MA, PsyD, PhD'], 'neuro' => [], 'ol' => false],
        ];

        foreach ($universities as $uni) {
            AcademiaUniversity::create([
                'state_id' => $state->id,
                'name' => $uni['name'],
                'psychology_degrees' => $uni['psych'],
                'neuroscience_degrees' => $uni['neuro'],
                'has_online_options' => $uni['ol'],
            ]);
        }

        $residencies = [
            ['name' => 'Albany Medical Center', 'loc' => 'Albany', 'deg' => ['MD-DO']],
            ['name' => 'BronxCare Health System Psychiatry Residency Program', 'loc' => 'Bronx', 'deg' => ['MD-DO']],
            ['name' => 'Lincoln Medical and Mental Health Center', 'loc' => 'Bronx', 'deg' => ['MD-DO']],
            ['name' => 'One Brooklyn Health System/Brookdale Univ Hospital and Medical Center', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'Maimonides Medical Center Psychiatry Residency Program', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'Nassau University Medical Center', 'loc' => 'East Meadow', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Medicine at Mount Sinai/Beth Israel Psychiatry Residency Program', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Harlem Hospital Center', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'New York Medical College (Metropolitan) Psychiatry Residency Program', 'loc' => 'NY', 'deg' => ['MD-DO']],
            ['name' => 'Arnot Ogden Medical Center Psychiatry Residency Program', 'loc' => 'Elmira', 'deg' => ['MD-DO']],
            ['name' => 'NYU Grossman School of Medicine', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Creedmoor Psychiatric Center Psychiatry Residency Program', 'loc' => 'Queens Village', 'deg' => ['MD-DO']],
            ['name' => 'Stony Brook Medicine/University Hospital', 'loc' => 'Stony Brook', 'deg' => ['MD-DO']],
            ['name' => 'Montefiore Medical Center/Albert Einstein College of Medicine', 'loc' => 'Bronx', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Medicine at Mount Sinai/Mount Sinai Hospital Psychiatry Residency', 'loc' => 'Jonesboro', 'deg' => ['MD-DO']],
            ['name' => 'New York Presbyterian Hospital (Cornell Campus)', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'University of Rochester', 'loc' => 'Rochester', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Med at Mount Sinai/NYC Health and Hospitals Psychiatry Residency', 'loc' => 'Elmhurst', 'deg' => ['MD-DO']],
            ['name' => 'Richmond University Medical Center', 'loc' => 'Staten Island', 'deg' => ['MD-DO']],
            ['name' => 'Jamaica Hospital Medical Center Psychiatry Residency Program', 'loc' => 'Jamaica', 'deg' => ['MD-DO']],
            ['name' => 'University at Buffalo', 'loc' => 'Buffalo', 'deg' => ['MD-DO']],
            ['name' => 'Zucker School of Medicine at Hofstra/Northwell at Zucker Hillside Hospital', 'loc' => 'Glen Oaks', 'deg' => ['MD-DO']],
            ['name' => 'SUNY Downstate Health Sciences Univ Psychiatry Residency Program', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'SUNY Update Medical University', 'loc' => 'Syracuse', 'deg' => ['MD-DO']],
            ['name' => 'Westchester Medical Center', 'loc' => 'Valhalla', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Medicine at Mount Sinai/Morningside/West Psychiatry Residency', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Zucker School of Medicine at Hofstra/Northwell at Staten Island Univ', 'loc' => 'Staten Island', 'deg' => ['MD-DO']],
            ['name' => 'St. John\'s Episcopal Hospital-South Shore', 'loc' => 'Far Rockaway', 'deg' => ['MD-DO']],
            ['name' => 'St. Barnabas Hospital Psychiatry Residency Program', 'loc' => 'Bronx', 'deg' => ['MD-DO']],
            ['name' => 'Zucker School of Medicine at Hofstra/Northwell at Mather Hospital', 'loc' => 'Port Jefferson', 'deg' => ['MD-DO']],
            ['name' => 'One Brooklyn Health System/Interfaith Medical Center', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'Garnet Health Medical Center', 'loc' => 'Middletown', 'deg' => ['MD-DO']],
            ['name' => 'New York Presbyterian Hospital (Columbia Campus)/New York State Psychiatric Inst', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Stony Brook Medicine', 'loc' => 'Greenport', 'deg' => ['MD-DO']],
            ['name' => 'Nuvance Health Psychiatry Residency Program', 'loc' => 'Carmel Hamlet', 'deg' => ['MD-DO']],
            ['name' => 'Rochester General Hospital Psychiatry Residency Program', 'loc' => 'Rochester', 'deg' => ['MD-DO']],
            ['name' => 'Family Health Centers at NYU Langone', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'Mohawk Valley Health Systems, Inc', 'loc' => 'Utica', 'deg' => ['MD-DO']],
            ['name' => 'New York Medical College at St. Joseph\'s Medical Center', 'loc' => 'Yonkers', 'deg' => ['MD-DO']],
            ['name' => 'United Health Services Hospitals', 'loc' => 'Binghamton', 'deg' => ['MD-DO']],
            ['name' => 'Good Samaritan University Hospital Psychiatry Residency Program', 'loc' => 'Smithtown', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Medicine at Mount Sinai', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Icahn School of Medicine at Mount Sinai/NYC Health and Hospitals (Queens)', 'loc' => 'Jamaica', 'deg' => ['MD-DO']],
            ['name' => 'Zucker School of Medicine at Hofstra/Northwell Lenox Hill Hospital', 'loc' => 'New York', 'deg' => ['MD-DO']],
            ['name' => 'Urban Health Plan', 'loc' => 'Bronx', 'deg' => ['MD-DO']],
            ['name' => 'Woodhull Medical and Mental Health Center', 'loc' => 'Brooklyn', 'deg' => ['MD-DO']],
            ['name' => 'Albany Medical College', 'loc' => 'Albany', 'deg' => ['MD-PhD']],
            ['name' => 'Albert Einstein College of Medicine of Yeshiva University', 'loc' => 'Bronx', 'deg' => ['MD-PhD']],
            ['name' => 'Columbia University College of Physicians and Surgeons', 'loc' => 'New York', 'deg' => ['MD-PhD']],
            ['name' => 'Hofstra North Shore - LIJ School of Medicine', 'loc' => 'Hempstead', 'deg' => ['MD-PhD']],
            ['name' => 'Weill Cornell/Rockefeller/Sloan-Kettering Tri-Institutional MD/PhD Program', 'loc' => 'New York', 'deg' => ['MD-PhD']],
            ['name' => 'Mount Sinai School of Medicine', 'loc' => 'New York', 'deg' => ['MD-PhD']],
            ['name' => 'New York Medical College', 'loc' => 'Valhalla', 'deg' => ['MD-PhD']],
            ['name' => 'New York University School of Medicine', 'loc' => 'New York', 'deg' => ['MD-PhD']],
            ['name' => 'SUNY at Buffalo School of Medicine', 'loc' => 'Buffalo', 'deg' => ['MD-PhD']],
            ['name' => 'SUNY at Stony Brook Health Sciences Center', 'loc' => 'Stony Brook', 'deg' => ['MD-PhD']],
            ['name' => 'SUNY Downstate Medical Center College of Medicine', 'loc' => 'Brooklyn', 'deg' => ['MD-PhD']],
            ['name' => 'SUNY Upstate Medical University', 'loc' => 'Syracuse', 'deg' => ['MD-PhD']],
            ['name' => 'University of Rochester School of Medicine', 'loc' => 'Rochester', 'deg' => ['MD-PhD']],
        ];

        foreach ($residencies as $res) {
            AcademiaMedicalResidency::create([
                'state_id' => $state->id,
                'program_name' => $res['name'],
                'location' => $res['loc'],
                'degree_types' => $res['deg'],
            ]);
        }

        $facilities = [
            // State Institutions
            ['name' => 'Arms Acres', 'loc' => 'Carmel', 'type' => 'state_institution'],
            ['name' => 'Brylin Hospitals', 'loc' => 'Buffalo', 'type' => 'state_institution'],
            ['name' => 'Four Winds Hospital', 'loc' => 'Katonah', 'type' => 'state_institution'],
            ['name' => 'Four Winds Hospital', 'loc' => 'Saratoga Springs', 'type' => 'state_institution'],
            ['name' => 'Four Winds Hospital', 'loc' => 'Syracuse', 'type' => 'state_institution'],
            ['name' => 'Gracie Square Hospital', 'loc' => 'New York', 'type' => 'state_institution'],
            ['name' => 'Holliswood Hospital', 'loc' => 'Queens', 'type' => 'state_institution'],
            ['name' => 'Lenox Hill Hospital - Department of Psychiatry', 'loc' => 'New York', 'type' => 'state_institution'],
            ['name' => 'Lincoln Medical and Mental Health Center', 'loc' => 'Bronx', 'type' => 'state_institution'],
            ['name' => 'Rochester Mental Health Center', 'loc' => 'Rochester', 'type' => 'state_institution'],
            ['name' => 'Rye Hospital Center', 'loc' => 'Rye', 'type' => 'state_institution'],
            ['name' => 'Saint Vincent\'s Hospital', 'loc' => 'Westchester', 'type' => 'state_institution'],
            ['name' => 'Zucker Hillside Hospital', 'loc' => 'Glen Oaks', 'type' => 'state_institution'],

            // University Hospital (Client Placeholder from image 5)
            ['name' => 'Univ of Alabama at Birmingham Center for Psychiatric Medicine', 'loc' => 'Birmingham', 'type' => 'university_hospital'],

            // VA Facilities
            ['name' => 'Batavia VA Medical Center', 'loc' => 'Batavia', 'type' => 'va_facility'],
            ['name' => 'Bath VA Medical Center', 'loc' => 'Bath', 'type' => 'va_facility'],
            ['name' => 'Brooklyn VA Medical Center', 'loc' => 'Brooklyn', 'type' => 'va_facility'],
            ['name' => 'Buffalo VA Medical Center', 'loc' => 'Buffalo', 'type' => 'va_facility'],
            ['name' => 'Franklin Delano Roosevelt Hospital', 'loc' => 'Montrose', 'type' => 'va_facility'],
            ['name' => 'Northport VA Medical Center', 'loc' => 'Northport', 'type' => 'va_facility'],
            ['name' => 'Samuel S. Stratton Department of Veterans Affairs Medical Center', 'loc' => 'Albany', 'type' => 'va_facility'],
        ];

        foreach ($facilities as $fac) {
            AcademiaFacility::create([
                'state_id' => $state->id,
                'name' => $fac['name'],
                'location' => $fac['loc'],
                'type' => $fac['type'],
            ]);
        }
    }
}
